import {
  FaHouse,
  FaCheckDouble,
  FaUserShield,
  FaGlobe,
  FaUserTie,
  FaStopwatch,
  FaHandshakeAngle,
  FaTags,
  FaFileInvoiceDollar,
  FaCode,
  FaRobot,
  FaBuilding,
  FaCalculator,
  FaReceipt,
  FaChartLine,
  FaNetworkWired,
  FaLocationDot,
  FaEnvelope,
  FaPhone,
  FaLinkedin,
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaWhatsapp,
  FaCheck,
  FaStar,
  FaChevronDown,
  FaCommentDots,
  FaPaperPlane,
  FaXmark,
  FaMoon,
  FaSun,
  FaHeart,
  FaNewspaper,
  FaBriefcase,
  FaUser,
  FaCalendarDays,
  FaLink,
  FaArrowLeft,
  FaPlus,
  FaLayerGroup,
  FaVolumeHigh,
  FaVolumeXmark,
  FaPlay,
  FaPenToSquare,
  FaTrash,
  FaCrown,
  FaRightFromBracket,
  FaImage,
  FaVideo,
  FaCloudArrowUp,
  FaPause,
  FaChevronLeft,
  FaChevronRight,
  FaExpand,
  FaArrowRight,
  FaCamera,
  FaEye,
  FaEyeSlash,
  FaClock,
  FaLock,
  FaInbox,
  FaSpinner,
  FaUsers,
  FaMagnifyingGlass,
  FaArrowUpRightFromSquare,
  FaFileLines,
  FaFileArrowDown,
} from 'react-icons/fa6'

export const ICONS = {
  FaHouse,
  FaCheckDouble,
  FaUserShield,
  FaGlobe,
  FaUserTie,
  FaStopwatch,
  FaHandshakeAngle,
  FaTags,
  FaFileInvoiceDollar,
  FaCode,
  FaRobot,
  FaBuilding,
  FaCalculator,
  FaReceipt,
  FaChartLine,
  FaNetworkWired,
  FaLocationDot,
  FaEnvelope,
  FaPhone,
  FaLinkedin,
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaWhatsapp,
  FaCheck,
  FaStar,
  FaChevronDown,
  FaCommentDots,
  FaPaperPlane,
  FaXmark,
  FaMoon,
  FaSun,
  FaHeart,
  FaNewspaper,
  FaBriefcase,
  FaUser,
  FaCalendarDays,
  FaLink,
  FaArrowLeft,
  FaPlus,
  FaLayerGroup,
  FaVolumeHigh,
  FaVolumeXmark,
  FaPlay,
  FaPenToSquare,
  FaTrash,
  FaCrown,
  FaRightFromBracket,
  FaImage,
  FaVideo,
  FaCloudArrowUp,
  FaPause,
  FaChevronLeft,
  FaChevronRight,
  FaExpand,
  FaArrowRight,
  FaCamera,
  FaEye,
  FaEyeSlash,
  FaClock,
  FaLock,
  FaInbox,
  FaSpinner,
  FaUsers,
  FaMapMarkerAlt: FaLocationDot,
  FaSearch: FaMagnifyingGlass,
  FaCalendarAlt: FaCalendarDays,
  FaCloudUploadAlt: FaCloudArrowUp,
  FaExternalLinkAlt: FaArrowUpRightFromSquare,
  FaFileAlt: FaFileLines,
  FaFileDownload: FaFileArrowDown,
}

const Icon = ({ name, className = '' }) => {
  const Cmp = ICONS[name]
  if (!Cmp) {
    console.warn(`Icon "${name}" is missing in iconMap.jsx`)
    return null
  }
  return <Cmp className={className} />
}

export default Icon