import {
  FaHouse,
  FaCheckDouble,
  FaUserShield,
  FaGlobe,
  FaUserTie,
  FaStopwatch,
  FaHandshakeAngle,
  FaTags,
  FaFileInvoiceDollar,
  FaCode,
  FaRobot,
  FaBuilding,
  FaCalculator,
  FaReceipt,
  FaChartLine,
  FaNetworkWired,
  FaLocationDot,
  FaEnvelope,
  FaPhone,
  FaLinkedin,
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaWhatsapp,
  FaCheck,
  FaStar,
  FaChevronDown,
  FaCommentDots,
  FaPaperPlane,
  FaXmark,
  FaMoon,
  FaSun,
  FaHeart,
  FaNewspaper,
  FaBriefcase,
  FaUser,
  FaCalendarDays,
  FaLink,
  FaArrowLeft,
  FaPlus,
  FaLayerGroup,
  FaVolumeHigh,
  FaVolumeXmark,
  FaPlay,
  FaPenToSquare,
  FaTrash,
} from 'react-icons/fa6'

export const ICONS = {
  FaHouse,
  FaCheckDouble,
  FaUserShield,
  FaGlobe,
  FaUserTie,
  FaStopwatch,
  FaHandshakeAngle,
  FaTags,
  FaFileInvoiceDollar,
  FaCode,
  FaRobot,
  FaBuilding,
  FaCalculator,
  FaReceipt,
  FaChartLine,
  FaNetworkWired,
  FaLocationDot,
  FaEnvelope,
  FaPhone,
  FaLinkedin,
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaWhatsapp,
  FaCheck,
  FaStar,
  FaChevronDown,
  FaCommentDots,
  FaPaperPlane,
  FaXmark,
  FaMoon,
  FaSun,
  FaHeart,
  FaNewspaper,
  FaBriefcase,
  FaUser,
  FaCalendarDays,
  FaLink,
  FaArrowLeft,
  FaPlus,
  FaLayerGroup,
  FaVolumeHigh,
  FaVolumeXmark,
  FaPlay,
  FaPenToSquare,
  FaTrash,
}

const Icon = ({ name, className = '' }) => {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  return <Cmp className={className} />
}

export default Icon